ssh:
  authorized_keys:
    devops:
    - name: mrben-mansour
      state: present
      key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeLz0bfN+Z3TJFWgMbx4VgRNYuvK1uPk3p5HnQU3uvVqwf7eT6Xde3ioBvdG2EGiBHGS3RbL7Q4Co29mRA0HiLmxMcakTdFhI9q46MlGvqn9X3Ytj2ovTScLCqU9W/bP2lp1epjkW4kQkubhr/VGm6P76Ern69aGfRvRtTKGBzPRcVg+HfBLcykz4IITyef/QIyqY9CBbNxJXQCfxvUOKRWXHAmSYY5A2cCkGYWR1JLqymJ/Forrw+xDtMDi3m4kf5KEBM3bbKYXn3EfSlieQ0ILDc+RmTrivydMs9TOLNB0OTlJhpRfxIbnoVci4FZqNdIsFrrz/EHUti2ZObfdGD benmansour.mohamedrafik@kisio.com
    - name: astebel
      state: present
      key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAczEovkN7lbN0rPRt2a5kFBr1gGPcf0zyEeueiNaDiFilG7VA6QfexoeLKB/Y77oVYiPxKiO8rfJw+lma9whcUHj5NoRxV2VursQmXB/aiRrWidu58fKdrNXa4Ujm8Z63sksHYPzrG3mAxL/6e5MhPBb/vALRv+ogb30Szm/XBWzWU9M/LfIBWIX1qmOm+IxsHWIoM+hCs8H0CFgKaaWFc8NVjYRYojQCtxjGzTDeH1lB0LKp9XGzEA5DOUwHhx0raHfJ1HMt7mBP8raKOR9qSnASe2v5lIADWM1LXwaBbJJqdX/bdSmbkpBUzR3P6AgIR37vBd928Q+1LWFuWkcV antoine.stebel@kisio.com
    - name: nguyen
      state: present
      key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1wTtjIqnn+HIS3gb8wrOMdK5XiRi5oYLcR/dgOhgpsNu3HSY8dysGBkXj3+GfjOG20wyLEF+SZ8kCMs+OGctb3seq3E2soHwAHPjKq9erQRBaaXyV1f/jNuumMrlX7ewag1ITXf75J5nV5ZI+tpgnuY01eQD6GhXXRH5THJOISeHLGH5cBuf+q4O+xM8c78C4+TD4tSOMW3K7Q7yvx/Ku+GKgtUODe9ApxDbw4i8lZ+5JDjGgDQhFYLsImXZg1nDBF8cAYDgsJznkmjyUKi72LGS1izU9hrGcPbRoJ5Uq7JW9SarmjQIrxU47RdIfRU4AvEPHj0TmN09hdvCAnka9 nguyen@pckisio
    groupvars:
    - name: jenkins
      state: present
      key_pub: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD8fWeetfzM1qFbRnoyI/2sOsK5XiX1TfUvOYV5G27tOuXJU7CalB/PT5HJdniviNOpmw0H1KRrdyTtSyu8Lfp4+VeTsjgbJLhltCrI6sKUfCerA5eX67GSwSfl6aHuwXXqTSmaz25xuLCyYpoGoPP0+5UMsJ5sU7BDfvWmm/ljDAp8TQn5ZhpdYGM2BRxooqkztvYoO+osFsJkVjHV9zASZ0/6KDFVOwfandstttXCaiXh21jmvfurWDHHMYqpLpz/QldZKJRBK2JLUHcYQmmontNrfZRjQgQH3ifJpkjYu6CKILuh2PF5lFqHz0+10cRsybi96MOA1SkjELQZnZZ jenkins
ntp:
  settings:
  - name: ntp1
    server: ntp1
    option: iburst
  - name: ntp2
    server: ntp22
    option: iburst
